name: Continuous integration

on:
  push:
    paths-ignore:
      - '**.md'
      - '!src/**.md'
      - '!tests/**.md'
      - '.github'
      - '!.github/workflows'
  pull_request:
    paths-ignore:
      - '**.md'
      - '!src/**.md'
      - '!tests/**.md'
      - '.github'
      - '!.github/workflows'

jobs:
  test:
    name: 'Test (PHP: ${{ matrix.php-versions }}, OS: ${{ matrix.operating-systems }}, dependencies: ${{ matrix.dependencies }})'
    runs-on: ${{ matrix.operating-systems }}

    # STRATEGY
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        operating-systems: [ubuntu-latest, windows-latest, macos-latest]
        dependencies: ['lowest', 'stable']
      fail-fast: false

    steps:
      # SETUP
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, mbstring
          coverage: xdebug
      - name: Get Composer cache directory
        id: composer-cache-directory
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-directory.outputs.dir }}
          key: ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}_composer_dependencies-${{ matrix.dependencies }}_${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}_composer_dependencies-${{ matrix.dependencies }}
            ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}_composer
            ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}
            ${{ matrix.operating-systems }}
        id: composer-cache
      - name: Install dependencies (lowest)
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --no-interaction --no-progress --no-suggest --prefer-lowest
      - name: Install dependencies (stable)
        if: ${{ matrix.dependencies == 'stable' }}
        run: composer update --no-interaction --no-progress --no-suggest --prefer-stable

      # TESTS
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Run tests
        run: |
          mkdir -p var/coverage/report
          ./vendor/bin/phpunit

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: 'Coverage results (PHP ${{ matrix.php-versions }}, OS ${{ matrix.operating-systems }}, dependencies ${{ matrix.dependencies }})'
          path: ./var/coverage/report

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Get Composer cache directory
        id: composer-cache-directory
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-directory.outputs.dir }}
          key: ubuntu-latest_php7.4_composer_dependencies-stable_${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ubuntu-latest_php7.4_composer_dependencies-stable
            ubuntu-latest_php7.4_composer
            ubuntu-latest_php7.4
            ubuntu-latest
        id: composer-cache
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-suggest --prefer-stable

      # TESTS
      - name: Run lint
        run: ./vendor/bin/phpcs -s
